// Demo data for when Firebase/Calendar isn't configured
// This ensures the app shows something useful immediately

export const demoCalendarEvents = [
  {
    id: 'demo-1',
    title: 'Team Standup',
    start: new Date(new Date().setHours(9, 0, 0, 0)).toISOString(),
    end: new Date(new Date().setHours(9, 30, 0, 0)).toISOString(),
    source: 'google',
    type: 'meeting',
    color: '#5b8def',
  },
  {
    id: 'demo-2',
    title: 'Project Review with Prof. Sharma',
    start: new Date(new Date().setHours(11, 0, 0, 0)).toISOString(),
    end: new Date(new Date().setHours(12, 0, 0, 0)).toISOString(),
    source: 'google',
    type: 'meeting',
    color: '#5b8def',
  },
  {
    id: 'demo-3',
    title: 'Deep Work: Report Writing',
    start: new Date(new Date().setHours(14, 0, 0, 0)).toISOString(),
    end: new Date(new Date().setHours(16, 0, 0, 0)).toISOString(),
    source: 'ai',
    type: 'focus',
    color: '#f5a623',
  },
  {
    id: 'demo-4',
    title: 'Study Group — Data Structures',
    start: new Date(new Date().setHours(16, 30, 0, 0)).toISOString(),
    end: new Date(new Date().setHours(18, 0, 0, 0)).toISOString(),
    source: 'google',
    type: 'academic',
    color: '#9b72cf',
  },
  {
    id: 'demo-5',
    title: 'Gym Session',
    start: new Date(new Date().setHours(18, 30, 0, 0)).toISOString(),
    end: new Date(new Date().setHours(19, 30, 0, 0)).toISOString(),
    source: 'google',
    type: 'personal',
    color: '#4ecdc4',
  },
];

export const demoTasks = [
  {
    id: 'task-1',
    title: 'Submit ML Assignment',
    description: 'Complete the neural network implementation and submit via LMS',
    status: 'pending',
    priority: 'high',
    urgency: 'critical',
    effort: 'medium',
    type: 'academic',
    scheduled_time: new Date(new Date().setHours(15, 0, 0, 0)).toISOString(),
    deadline: new Date(new Date().setHours(23, 59, 0, 0)).toISOString(),
    source: 'gmail',
    created_at: new Date().toISOString(),
  },
  {
    id: 'task-2',
    title: 'Review pull request #142',
    description: 'Code review for the authentication module refactor',
    status: 'pending',
    priority: 'medium',
    urgency: 'soon',
    effort: 'low',
    type: 'work',
    scheduled_time: new Date(new Date().setHours(10, 0, 0, 0)).toISOString(),
    source: 'app',
    created_at: new Date().toISOString(),
  },
  {
    id: 'task-3',
    title: 'Prepare presentation slides',
    description: 'Slide deck for tomorrow\'s project review meeting',
    status: 'in_progress',
    priority: 'high',
    urgency: 'urgent',
    effort: 'high',
    type: 'academic',
    scheduled_time: new Date(new Date().setHours(13, 0, 0, 0)).toISOString(),
    deadline: new Date(new Date().setHours(11, 0, 0, 0) + 86400000).toISOString(),
    source: 'app',
    created_at: new Date().toISOString(),
  },
  {
    id: 'task-4',
    title: 'Reply to internship email',
    description: 'Follow up on the summer internship confirmation from TechCorp',
    status: 'done',
    priority: 'high',
    urgency: 'comfortable',
    effort: 'low',
    type: 'work',
    source: 'gmail',
    created_at: new Date().toISOString(),
    completed_at: new Date().toISOString(),
  },
  {
    id: 'task-5',
    title: 'Buy groceries',
    description: 'Milk, eggs, bread, and vegetables for the week',
    status: 'pending',
    priority: 'low',
    urgency: 'comfortable',
    effort: 'low',
    type: 'personal',
    source: 'whatsapp',
    created_at: new Date().toISOString(),
  },
];

export const demoTriageItems = [
  {
    id: 'triage-1',
    title: 'Database assignment due Friday',
    description: 'Found in email from Prof. Sharma — "Please submit the ER diagram assignment by Friday 5 PM"',
    source: 'gmail',
    sender: 'Prof. Sharma',
    suggested_time: new Date(new Date().setHours(14, 0, 0, 0) + 172800000).toISOString(),
    priority: 'high',
    type: 'academic',
    created_at: new Date().toISOString(),
  },
  {
    id: 'triage-2',
    title: 'Team dinner this Saturday',
    description: 'WhatsApp message from Ravi — "Hey, team dinner at 8pm Saturday, you in?"',
    source: 'whatsapp',
    sender: 'Ravi',
    suggested_time: new Date(new Date().setHours(20, 0, 0, 0) + 259200000).toISOString(),
    priority: 'low',
    type: 'personal',
    created_at: new Date().toISOString(),
  },
  {
    id: 'triage-3',
    title: 'Code review deadline moved up',
    description: 'Email from lead dev — "Can you complete the PR review by end of day tomorrow?"',
    source: 'gmail',
    sender: 'Alex Chen',
    suggested_time: new Date(new Date().setHours(17, 0, 0, 0) + 86400000).toISOString(),
    priority: 'medium',
    type: 'work',
    created_at: new Date().toISOString(),
  },
];

export const demoAgentLog = [
  {
    agent: 'Planner',
    action: 'Ranked your tasks by urgency × importance × effort',
    detail: 'ML Assignment moved to #1 — deadline is tonight and effort is medium. Presentation prep is #2 — high effort but deadline is tomorrow.',
    timestamp: new Date(Date.now() - 300000).toISOString(),
  },
  {
    agent: 'Conflict Resolver',
    action: 'Detected a scheduling overlap',
    detail: 'Your "Deep Work: Report Writing" block (2–4 PM) overlaps with the ML Assignment\'s ideal focus window. Proposed moving report writing to tomorrow morning.',
    timestamp: new Date(Date.now() - 240000).toISOString(),
  },
  {
    agent: 'Scheduler',
    action: 'Found a gap for your presentation prep',
    detail: 'Slotted 90 minutes of presentation work into the 12:30–2 PM window after your meeting with Prof. Sharma.',
    timestamp: new Date(Date.now() - 180000).toISOString(),
  },
  {
    agent: 'Communication',
    action: 'Drafted a WhatsApp reminder',
    detail: '"Hey! Just a heads up — your ML assignment is due tonight at midnight. You\'ve got a 2-hour block at 3 PM to wrap it up 💪"',
    timestamp: new Date(Date.now() - 120000).toISOString(),
  },
];

export const demoConflicts = [
  {
    id: 'conflict-1',
    events: [demoCalendarEvents[2], { 
      id: 'task-1-block', 
      title: 'ML Assignment Focus Block', 
      start: new Date(new Date().setHours(15, 0, 0, 0)).toISOString(),
      end: new Date(new Date().setHours(17, 0, 0, 0)).toISOString(),
      source: 'ai',
      type: 'focus',
    }],
    overlapMinutes: 60,
    suggestions: [
      { label: 'Move report to tomorrow morning', action: 'reschedule_first' },
      { label: 'Split ML work into two sessions', action: 'split_second' },
      { label: 'Keep both, I\'ll manage', action: 'dismiss' },
    ],
  },
];
